package cs

import (
	"fmt"

	"github.com/consensys/gnark-crypto/field/koalabear"
	"github.com/consensys/iop/pas/sym"
	"github.com/consensys/iop/pas/univariate"
)

type IOPConfig struct {
	// CacheMe if CacheMe is set, the constraint generated by the IOP is stored in the cache and not recorded
	CacheMe bool
}

type IOPOption func(config *IOPConfig) error

func WithCaching() IOPOption {
	return func(config *IOPConfig) error {
		config.CacheMe = true
		return nil
	}
}

// ===================== Grand Product =====================

// NewGrandProductIOP computes the grand product polynomial R such that:
//
//	R[0] = 1
//	R[i+1] = R[i] * E1(ID1[i]) / E2(ID2[i])
//
// where ID1 = IDs[:len(IDs)/2], ID2 = IDs[len(IDs)/2:],
// E1 = Π_j (ID1[j] - challenge) and E2 = Π_j (ID2[j] - challenge).
//
// It adds R and R_shifted (R[i+1 mod N]) to the trace, then records the constraint
// E2 * R_shifted - E1 * R = 0 mod X^N-1.
func NewGrandProductIOP(S *System, IDs []string, IDresult string, challenge Challenge, opts ...IOPOption) error {

	// build the config
	var config IOPConfig
	for _, opt := range opts {
		if err := opt(&config); err != nil {
			return err
		}
	}

	// ensure len(IDs) is even, split into numerator and denominator halves
	if len(IDs)%2 != 0 {
		return fmt.Errorf("IDs must have even length, got %d", len(IDs))
	}
	half := len(IDs) / 2
	ID1 := IDs[:half]
	ID2 := IDs[half:]

	if err := ensureChallengeInTrace(S, challenge); err != nil {
		return err
	}
	challengeColumn := S.Trace[challenge.Name]

	// build P1 and P2 maps, including the challenge column so EvalPointWise can resolve it
	P1 := make(map[string]*univariate.Polynomial, len(ID1)+1)
	for _, id := range ID1 {
		P1[id] = S.Trace[id]
	}
	P1[challenge.Name] = challengeColumn

	P2 := make(map[string]*univariate.Polynomial, len(ID2)+1)
	for _, id := range ID2 {
		P2[id] = S.Trace[id]
	}
	P2[challenge.Name] = challengeColumn

	// build E1 = Π_j (ID1[j] - gamma), E2 = Π_j (ID2[j] - gamma)
	E1 := GetProductConstraint(ID1, challenge.Name)
	E2 := GetProductConstraint(ID2, challenge.Name)

	// compute R in Lagrange basis
	R, err := univariate.BuildGrandProduct(
		[2]map[string]*univariate.Polynomial{P1, P2},
		[2]sym.Expr{E1, E2},
		S.N,
		univariate.WithOutputBasis(univariate.Lagrange),
	)
	if err != nil {
		return err
	}
	if _, ok := S.Trace[IDresult]; ok {
		return fmt.Errorf("%s already recorded in the trace (name already taken)", IDresult)
	}
	S.Trace[IDresult] = &R

	// build RS as an explicit Lagrange polynomial with RS[i] = R[i+1 mod N].
	// We store it as a regular polynomial (not a ShallowCopy+Shift) so that FFT-based
	// operations in ComputeQuotient see the correct shifted evaluations directly.
	rsID := IDresult + "_shifted"
	RSCoeffs := make([]koalabear.Element, S.N)
	for i := 0; i < S.N; i++ {
		RSCoeffs[i] = R.GetCoefficient((i + 1) % S.N)
	}
	RS, err := univariate.NewInterpolatedPolynomial(RSCoeffs, rsID)
	if err != nil {
		return err
	}
	if _, ok := S.Trace[rsID]; ok {
		return fmt.Errorf("%s already recorded in the trace (name already taken)", rsID)
	}
	S.Trace[rsID] = &RS

	// record the grand product constraint: E2 * RS - E1 * R = 0 mod X^N-1
	C := GetGrandProductConstraint(E1, E2, IDresult, rsID)
	if config.CacheMe {
		S.CachedConstraints = append(S.CachedConstraints, C)
	} else {
		S.Constraints = append(S.Constraints, C)
	}

	return nil
}
