package system

import (
	"fmt"

	"github.com/consensys/gnark-crypto/field/koalabear"
	"github.com/consensys/iop/pas/sym"
	"github.com/consensys/iop/pas/univariate"
)

type Challenge struct {
	Name  string
	Value koalabear.Element
}

type Config struct {
	// CacheMe if CacheMe is set, the constraint generated by the IOP is stored in the cache and not recorded
	CacheMe bool
}

type Option func(config *Config) error

func CacheMe() Option {
	return func(config *Config) error {
		config.CacheMe = true
		return nil
	}
}

// addChallengeInTrace adds challenge as a constant column to S.Trace if it has a
// name and is not already present. This allows functions like NewSimpleIOP and
// NewGrandProductIOP to be called directly (without Protocol.SendMeAChallenge) while
// still resolving placeholder references during pointwise evaluation and brute-force checks.
func addChallengeInTrace(S *System, challenge Challenge) error {
	if challenge.Name == "" {
		return nil
	}
	if _, ok := S.Trace[challenge.Name]; ok {
		return nil
	}
	col, err := univariate.NewConstantPolynomial(challenge.Value)
	if err != nil {
		return err
	}
	S.Trace[challenge.Name] = &col
	return nil
}

// ComputableColumn special column that can be encoded with a formula F	, like Lagrange column.
type ComputableColumn struct {
	id  string                                    // ID of the computable column
	F   func(koalabear.Element) koalabear.Element // function F encoding the column (e.g. ω^i/N (z^N-1)/(1-ω^i) for Lagrange_i_N)
	Gen func() univariate.Polynomial              // generate the column -> it is the evaluation of F on the domain of size N
}

// GetComputationableColumn atm there is only one type of computableColumns, but when there will be more
// we need to switch on the id to know which type is it, and return the correct colum
func GetComputationableColumn(id string) (ComputableColumn, error) {

	// TODO when there is more than one type of computable column, switch on id to know which type is it
	// atm there only one type, LagrangeColumn
	return NewLagrangeColumn(id)
}

// AddComputableColumn returns a computable column, that is a column encoded by a formula.
// If it exists, we don't throw an error, as the column might be generated from different IOPs.
func AddComputableColumn(S *System, c ComputableColumn) {
	col := c.Gen()
	if _, ok := S.Trace[c.id]; ok {
		return
	}
	S.Trace[c.id] = &col
}

// BuildColumn computes a new polynomial Q (new column in the trace) such that ith that Q =E(IDs)
// Returns the constraint Q-E(IDs), but does not record it. It is up to the caller to record it in the system.
func BuildColumn(S *System, E sym.Expr, IDresult string) (Constraint, error) {

	sum, err := univariate.EvalPointWise(S.Trace, E, S.N)
	if err != nil {
		return nil, err
	}

	// record the result polynomial
	if _, ok := S.Trace[IDresult]; ok {
		return nil, fmt.Errorf("%s already recorded in the trace (name already taken)", IDresult)
	}
	S.Trace[IDresult] = &sum

	// record the constraint
	C := E.Sub(sym.NewVar(IDresult))

	return C, nil
}
