package system

import (
	"fmt"

	"github.com/consensys/gnark-crypto/field/koalabear"
	"github.com/consensys/iop/pas/sym"
	"github.com/consensys/iop/pas/univariate"
)

type Challenge struct {
	Name  string
	Value koalabear.Element
}

type IOPConfig struct {
	// CacheMe if CacheMe is set, the constraint generated by the IOP is stored in the cache and not recorded
	CacheMe bool
}

type IOPOption func(config *IOPConfig) error

func CacheMe() IOPOption {
	return func(config *IOPConfig) error {
		config.CacheMe = true
		return nil
	}
}

// ensureChallengeInTrace adds challenge as a constant column to S.Trace if it has a
// name and is not already present. This allows functions like NewSimpleIOP and
// NewGrandProductIOP to be called directly (without Protocol.SendMeAChallenge) while
// still resolving placeholder references during pointwise evaluation and brute-force checks.
func ensureChallengeInTrace(S *System, challenge Challenge) error {
	if challenge.Name == "" {
		return nil
	}
	if _, ok := S.Trace[challenge.Name]; ok {
		return nil
	}
	col, err := univariate.NewConstantPolynomial(challenge.Value)
	if err != nil {
		return err
	}
	S.Trace[challenge.Name] = &col
	return nil
}

// NewColumn computes a new polynomial Q (new column in the trace) with that Q =E(IDs)
// Record the constraint Q-E(IDs)=0
func NewColumn(S *System, E sym.Expr, IDresult string, opts ...IOPOption) error {

	// build the config file
	var config IOPConfig
	for _, opt := range opts {
		err := opt(&config)
		if err != nil {
			return err
		}
	}

	sum, err := univariate.EvalPointWise(S.Trace, E, S.N, univariate.WithOutputBasis(univariate.Lagrange))
	if err != nil {
		return err
	}

	// record the result polynomial
	if _, ok := S.Trace[IDresult]; ok {
		return fmt.Errorf("%s already recorded in the trace (name already taken)", IDresult)
	}
	S.Trace[IDresult] = &sum

	// record the constraint
	C := E.Sub(sym.NewVar(IDresult))
	if config.CacheMe {
		S.CachedConstraints = append(S.CachedConstraints, C)
	} else {
		S.Constraints = append(S.Constraints, C)
	}

	return nil
}

// BuildColumnWithChallenge computes a new polynomial Q (so new column in the trace) so that Q =E(IDs, Challenge), and adds the constraint
// Q - E(IDs, Challenge)
func BuildColumnWithChallenge(S *System, E sym.Expr, IDresult string, challenge koalabear.Element, opts ...IOPOption) error {

	// build the config file
	var config IOPConfig
	for _, opt := range opts {
		err := opt(&config)
		if err != nil {
			return err
		}
	}

	// get the name of the challenge -> it is the unique placeholder in E. If E has more than one placeholder, throw an error
	ph := sym.RemoveDuplicates(E.Placeholders())
	if len(ph) != 1 {
		return fmt.Errorf("expected exactly one placeholder for a challenge, got %d: %v", len(ph), ph)
	}
	challengeName := ph[0]

	if err := ensureChallengeInTrace(S, Challenge{Name: challengeName, Value: challenge}); err != nil {
		return err
	}

	sum, err := univariate.EvalPointWise(S.Trace, E, S.N, univariate.WithOutputBasis(univariate.Lagrange))
	if err != nil {
		return err
	}

	// record the result polynomial
	if _, ok := S.Trace[IDresult]; ok {
		return fmt.Errorf("%s already recorded in the trace (name already taken)", IDresult)
	}
	S.Trace[IDresult] = &sum

	// record the constraint
	C := E.Sub(sym.NewVar(IDresult))
	if config.CacheMe {
		S.CachedConstraints = append(S.CachedConstraints, C)
	} else {
		S.Constraints = append(S.Constraints, C)
	}

	return nil
}
